version: '3'
services:
  api-tests-runner:
    tty: true
    build:
      context: .
      target: api-tests-runner
      dockerfile: Dockerfile.api.tests
    ports:
      - '8800:8800'
    command: ['sh', '-c', 'yarn test:api']
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - '27017'
    volumes:
      - database:/data/db
  mongo-seed:
    build:
      context: .
      target: mongo-seed
      dockerfile: Dockerfile.api.tests
    links:
      - db
    depends_on:
      - db

volumes:
  database:
