version: '3.7'
services:
  api-tests-runner:
    build:
      context: .
      target: api-tests-runner
      dockerfile: Dockerfile.api.tests
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: ['sh', '-c', 'yarn test:api']
    depends_on:
      - mongo-seed

  mongo-seed:
    build:
      context: .
      target: mongo-seed
      dockerfile: Dockerfile.api.tests
    links:
      - db
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - '27017'
    volumes:
      - database:/data/db

volumes:
  database:
