version: "3"
services:

  api:
    ports:
      - "8800:8800"
    build: .
    command: ["sh", "-c", "yarn mongo-indexes && yarn api"]
    restart: on-failure

  processor:
    build: .
    command: ["sh", "-c", "scripts/wq.sh && yarn processor"]
    restart: on-failure

  blockrange:
    build: .
    command: ["sh", "-c", "scripts/wq.sh && yarn blockrange"]
    restart: on-failure

  filler:
    build: .
    command: ["sh", "-c", "scripts/wq.sh && yarn filler ${FILLER_FLAGS}"]
    restart: on-failure
