version: '3.7'
services:
  api:
    image: ${DOCKER_REGISTRY}/alienworlds_api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        NODE_ENV: '${NODE_ENV}'
      cache_from:
        - ${DOCKER_REGISTRY}/alienworlds_api
    environment:
      NODE_ENV: '${NODE_ENV}'
    restart: on-failure
    ports:
      - '8800:8800'
