version: "3"
services:

  api:
    volumes:
      - ./:/var/www/api

  processor:
    volumes:
      - ./:/var/www/api

  blockrange:
    volumes:
      - ./:/var/www/api

  filler:
    volumes:
      - ./:/var/www/api

  db:
    image: mongo
    restart: always
    ports:
      - "27017"
    volumes:
      - database:/data/db

  queue: # login guest:guest
    image: rabbitmq:management
    restart: always
    ports:
      - "5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  database:
