version: '3.7'
services:
  api:
    command:
      [
        'sh',
        '-c',
        'yarn setup-database --url ${MONGO_URL} --name ${MONGO_DB_NAME} && yarn api:dev',
      ]
    depends_on:
      - db
    volumes:
      - ./:/var/www/api

  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db

  apidoc:
    image: redocly/redoc
    depends_on:
      - api
    environment:
      - PAGE_TITLE="Alien Worlds API"
      - SPEC_URL=http://localhost:8800/v1/alienworlds/docs/json
    ports:
      - '8900:80'

volumes:
  database:
