FROM mongo AS mongo-seed

COPY tests/api/fixtures/*.seed.json /

## drop existing test db and reimport seed for fresh test
CMD mongoimport --host db --db alienworlds_mainnet --collection mines --type json --file /mines.seed.json --jsonArray --drop && \
    mongoimport --host db --db alienworlds_mainnet --collection assets --type json --file /assets.seed.json --jsonArray --drop && \
    mongoimport --host db --db alienworlds_mainnet --collection nfts --type json --file /nfts.seed.json --jsonArray --drop

FROM node:17-alpine3.12 AS api-tests-runner

RUN apk add --no-cache --virtual build-dependencies python2 g++ make

RUN apk add curl

RUN mkdir -p /var/www/api

ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

COPY . /var/www/api
COPY .env-test /var/www/api/.env-test

WORKDIR /var/www/api

RUN yarn
RUN yarn build
