version: '3.7'
services:
  api:
    image: ${DOCKER_REGISTRY}/alienworlds_api
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY}/alienworlds_api
    restart: on-failure
    ports:
      - '8800:8800'

  processor:
    image: ${DOCKER_REGISTRY}/alienworlds_processor
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY}/alienworlds_processor
    restart: on-failure

  blockrange:
    image: ${DOCKER_REGISTRY}/alienworlds_blockrange
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY}/alienworlds_blockrange
    restart: on-failure

  filler:
    image: ${DOCKER_REGISTRY}/alienworlds_filler
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY}/alienworlds_filler
    restart: on-failure
