FROM mongo AS mongo-seed

COPY tests/api/fixtures/* /

## drop existing test db and reimport seed for fresh test
CMD mongoimport --host db --db alienworlds_mainnet --collection mines --type json --file /mines.seed.json --jsonArray --drop && \ 
    mongoimport --host db --db alienworlds_mainnet --collection nfts --type json --file /nfts.seed.json --jsonArray --drop

FROM node:17-alpine3.12 AS api-tests-runner

ENV NODE_ENV=api-tests

RUN apk add curl
RUN npm install -g typescript

RUN mkdir -p /var/www/api/tests/api

ADD scripts /var/www/api/scripts
ADD src /var/www/api/src
ADD tests/environments /var/www/api/tests/environments
ADD tests/api /var/www/api/tests/api

COPY package.json tsconfig.json yarn.lock jest.config.js jest.config.api.js /var/www/api/

WORKDIR /var/www/api

RUN yarn
RUN yarn build-tests:api
