version: '3.7'
services:
  api:
    command: ['sh', '-c', 'yarn mongo-indexes && yarn api']
    depends_on:
      - db
    volumes:
      - ./:/var/www/api

  processor:
    command: ['sh', '-c', 'scripts/wq.sh && yarn processor']
    depends_on:
      - queue
    volumes:
      - ./:/var/www/api

  blockrange:
    command: ['sh', '-c', 'scripts/wq.sh && yarn blockrange']
    depends_on:
      - queue
    volumes:
      - ./:/var/www/api

  filler:
    command:
      ['sh', '-c', 'scripts/wq.sh && flags="${FILLER_FLAGS}" yarn filler']
    depends_on:
      - queue
    volumes:
      - ./:/var/www/api

  db:
    image: mongo
    restart: always
    ports:
      - '27017'
    volumes:
      - database:/data/db

  queue: # login guest:guest
    image: rabbitmq:management
    restart: always
    ports:
      - '5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 30s
      timeout: 10s
      retries: 5

  apidoc:
    image: redocly/redoc
    depends_on:
      - api
    environment:
      - PAGE_TITLE="Alien Worlds API"
      - SPEC_URL=http://localhost:8800/v1/alienworlds/docs/json
    ports:
      - '8900:80'

volumes:
  database:
