FROM node:17-alpine3.12

ENV NODE_ENV=api-tests

RUN apk add curl
RUN npm install -g typescript

RUN mkdir -p /var/www/api/tests/api

ADD scripts /var/www/api/scripts
ADD src /var/www/api/src
ADD tests/environments /var/www/api/tests/environments
ADD tests/api /var/www/api/tests/api

COPY package.json tsconfig.json yarn.lock babel.config.js jest.config.js jest.config.api.js /var/www/api/

WORKDIR /var/www/api

RUN yarn
RUN yarn build-tests:api
