version: "3"
services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile.api.tests
    ports:
      - "8800:8800"
    command: ["sh", "-c", "yarn mongo-indexes && yarn test:api"]

  db:
    image: mongo
    restart: always
    ports:
      - "27017"
    volumes:
      - database:/data/db

volumes:
  database:
