version: "3"
services:
  api:
    extends:
      file: docker-compose.common.yml
      service: common
    ports:
      - "8800:8800"
    command: ["sh", "-c", "yarn api"]

  processor:
    extends:
      file: docker-compose.common.yml
      service: common
    command: ["sh", "-c", "scripts/wq.sh && yarn processor"]

  blockrange:
    extends:
      file: docker-compose.common.yml
      service: common
    command: ["sh", "-c", "scripts/wq.sh && yarn blockrange"]

  filler:
    extends:
      file: docker-compose.common.yml
      service: common
    command: ["sh", "-c", "scripts/wq.sh && yarn filler ${FILLER_FLAGS}"]

  db:
    image: mongo
    restart: always
    ports:
      - "27017"
    volumes:
      - database:/data/db

  queue: # login guest:guest
    image: rabbitmq:management
    restart: always
    ports:
      - "5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  database:
