FROM mongo

COPY mines.seed.json /mines.seed.json
## drop existing test db and reimport seed for fresh test
CMD mongoimport --host db --db alienworlds_mainnet --collection mines --type json --file /mines.seed.json --jsonArray --drop
