version: "3"
services:
  api-tests:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.api.tests
    ports:
      - "8800:8800"
    command: ["sh", "-c", "yarn test:api"]
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017"
    volumes:
      - database:/data/db

volumes:
  database:
