/* eslint-disable @typescript-eslint/no-var-requires */
const config = require('./jest.config.js');

module.exports = {
  ...config,
  verbose: true,
  preset: 'ts-jest',
  testEnvironment: 'jest-environment-node',
  testMatch: ['**/__tests__/**/*.unit.test.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!**/use-case.ts',
    '!**/route.ts',
    '!**/*.fixture.ts',
    '!**/*.mock.ts',
    '!**/*.error.ts',
    '!**/__tests__/**',
    '!**/__mocks__/**',
    '!**/schemas/**',
    '!src/**/index.ts',
    '!src/**/*.repository.ts',
    '!src/**/*.service.ts',
    '!src/**/*.enums.ts',
    '!src/**/*.dtos.ts',
    '!src/**/*.types.ts',
    '!src/**/*.route.ts',
    '!src/**/api.routes.ts',
    '!src/**/worker.ts',
    '!src/**/ioc.config.ts',
    '!src/**/api.ioc.utils.ts',
    '!src/**/*.ioc.config.ts',
    '!src/**/eos-rpc.source.ts',
    '!src/**/state-history.source.ts',
  ],
};
