export const StateReceiver = jest.fn(() => ({
  parseDate: jest.fn(),
  registerBlockHandler: jest.fn(),
  registerDoneHandler: jest.fn(),
  registerTraceHandler: jest.fn(),
  registerDeltaHandler: jest.fn(),
  registerProgressHandler: jest.fn(),
  registerForkHandler: jest.fn(),
  registerConnectedHandler: jest.fn(),
  status: jest.fn(),
  start: jest.fn(),
  restart: jest.fn(),
  destroy: jest.fn(),
  requestBlocks: jest.fn(),
  handleFork: jest.fn(),
  receivedBlock: jest.fn(),
}));
