name: lint

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_REGISTRY: ghcr.io/alien-worlds
      FILLER_FLAGS:
    steps:
      - uses: actions/checkout@v2

      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v1
      #
      #      - name: Docker meta
      #        id: meta
      #        uses: docker/metadata-action@v3
      #        with:
      #          images: ghcr.io/alien-worlds/alienworlds_api

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Build and push
      #        uses: docker/build-push-action@v2
      #        with:
      #          pull: true
      #          push: true
      #          tags: ${{ steps.meta.outputs.tags }}

      # - name: Building Containers (using GHCR Registry as Cache)
      #   run: docker compose build --pull

      - name: Building dependencies
        run: docker compose run api yarn

      - name: Running ESLint
        run: docker compose run api yarn lint-es

      - name: Running Prettier
        run: docker compose run api yarn lint-prettier

      - name: Danger
        uses: danger/danger-js@9.1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List of Docker Images
        run: docker images

      # - name: Uploading Containers to Registry
      #  run: docker compose push
