name: lint

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_REGISTRY: ghcr.io/alien-worlds
      FILLER_FLAGS:
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building Containers (using GHCR Registry as Cache)
        run: docker compose build --pull

      - name: Building dependencies
        run: docker compose run api yarn

      - name: Running ESLint
        run: docker compose run api yarn lint

      - name: Running Prettier
        run: docker compose run api yarn lint-prettier

      - name: Uploading Containers to Registry
        run: docker compose push
