name: lint

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Building dependencies
        run: docker compose run api yarn

      - name: Running ESLint
        run: docker compose run api yarn lint
