name: lint

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
    env:
      DOCKER_REGISTRY: ghcr.io/alien-worlds
      FILLER_FLAGS: ''
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building dependencies
        run: docker compose run api yarn

      - name: Running ESLint
        run: docker compose run api yarn lint-es

      - name: Running Prettier
        run: docker compose run api yarn lint-prettier

      - name: Generating OpenAPI definition
        run: docker compose -f docker-compose.yml -f docker-compose.apigen.yml run apigen && docker compose down

      - name: Generating Redoc
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DACOCOBOT_PAT }}
          publish_dir: ./openapi
          publish_branch: docs
