name: Lint

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  docker:
    name: "Build Docker"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: read
    env:
      DOCKER_REGISTRY: ghcr.io/alien-worlds
      FILLER_FLAGS:
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building dependencies
        run: docker compose run api yarn

  formatting:
    name: "Code Formatting"
    depends_on: [docker]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: read
    steps:
      - name: Running ESLint
        run: docker compose run api yarn lint-es

      - name: Running Prettier
        run: docker compose run api yarn lint-prettier
